name = "remix"
workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"

kv_namespaces = [
  { binding = "POSTS", id = "cd19a6e249894b7aaabe4728882832b6" }
]

[site]
  bucket = "./public"

[build]
  command = "npm run build"

[vars]
WORDPRESS_URL="https://wordpress.org/news/"

[triggers]
crons = ["*/10 * * * *"]